[package]
name = "apex-rs-postcard"
version = "0.1.0"
edition = "2021"
authors = ["Sven Friedrich <sven.friedrich@dlr.de>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
postcard = {version = "1.0", default-features = false }
arrayvec = {version = "0.7", default-features = false }

apex-rs = {git = "https://github.com/aeronautical-informatics/apex-rs.git"}
